### ISSUE TITLE
Compilation Errors

### ISSUE THREAD

**Issue by YHVHvx** [hzqst/Syscall-Monitor#2]
Heyo! I have troubles with compilation from scratch source code Syscall-Monitor.
That seems like many variables and structs is missing or wrong. At current source code i have over 150 various compilation errors. Examples:
1) cls_get_process_curdir not defined in cls_protocol of Protocol.h header.
2) svc_nt_open_thread, svc_nt_createopen_mutant, not declared in svc_protocol of Protocol.h header.
3) svc_nt_open_thread_data, svc_nt_createopen_mutant_data, svc_nt_createopen_dirobj_data not declared as struct in Protocol.h header.
etc
I think that you include old version of Protocol.h(which is root of building driver problems) and will be nice replace it with last actual header for fixing this miss codes.
Thank you! With best regards, Leon.

**Comment by hzqst** [comment]
the protocol.h has been updated
