### ISSUE TITLE
QT libraries missing?

### ISSUE THREAD

**Issue by Alexdon9** [hzqst/Syscall-Monitor#5]
May you upload the QT libraries? they are missing in latest commit, its a pain to download 1GB+ from QT website.

**Comment by hzqst** [comment]
Sorry but it's not possible to upload more than 1GB+ files to the github repository, you could get them from: http://download.qt.io/official_releases/qt/ and it will take you only few hours to download

**Comment by Alexdon9** [comment]
Hello, I mean the dynamic libraries only (Qt5Widgets.dll, Qt5Gui.dll, Qt5Core.dll, Qt5Network.dll )

**Comment by hzqst** [comment]
bin64.zip uploaded, x64 binaries only.

**Comment by Alexdon9** [comment]
Thank you, worked.
